backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://pslp-site-in-dev.netlify.app
display_url: https://pslp-site-in-dev.netlify.app
logo_url: https://pslp-site-in-dev.netlify.app/images/logo.png
locale: 'en'

media_folder: static/assets/img
public_folder: assets/img
collections:
  - name: 'homepage'
    label: 'Homepage Configuration'
    description: 'You can enable or disable + edit the many parts of your homepage. Only thing you cannot do is reorder these elements on the homepage as this is hard-coded. If you want to move around sections, contact me and provide the order of appearance for each section.'
    folder: 'data/en'
    create: false
    delete: false
    editor:
      preview: true
    fields:
      - label: 'Banner Settings'
        name: 'banner'
        widget: 'banner'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'select', options: ["true", "false"], hint: 'Select true to activate the section on the homepage. Select false to make the section disappear.' }
          - { label: 'Headline', name: 'title', widget: 'string', required: false, hint: 'This is the main headline for this section of your homepage, appearing in bold. I made this field optional in case you are fine with having just text but no headline above.' }
          - { label: 'Content', name: 'content', widget: 'string', required: false, hint: 'This is the text that appears below your headline. I made this field optional in case you are fine with having a headline without text below.'}
          - { label: 'Image', name: 'image', widget: 'image', hint: 'Chose an image to illustrate this section'}
          - label: 'Button'
            name: 'button'
            widget: 'button'
            fields:
              - { label: 'Enable', name: 'enable', widget: 'select', options: ["true", "false"], hint: 'Select true to activate the button on this section. Select false to make the button disappear.' }
              - { label: 'Text on Button', name: 'label', widget: 'string', hint: 'Text appearing on the button, keep it short.'}

      - label: 'Feature Settings'
        name: 'features'
        widget: 'features'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'select', options: ["true", "false"], hint: 'Select true to activate the section on the homepage. Select false to make the section disappear.' }
          - { label: 'Headline', name: 'title', widget: 'string', hint: 'This is the main headline for this section of your homepage, appearing in bold.' }
          - { label: 'Image', name: 'image', widget: 'image', hint: 'Chose an image to illustrate this section'}
          - label: 'Left-side features'
            name: 'left_side'
            widget: 'list'
            allow_add: false
            summary: '{{fields.title}} - {{fields.icon}} - {{field.content}}'
            fields:
              - { label: 'Feature 1 Title', name: 'title', widget: 'string', hint: 'Name of this feature'}
              - { label: 'Icon', name: 'icon', widget: 'image', required: false, hint: 'Find an icon that comes with your feature. Icons are nice as they complement well the designs, and clients like visuals. You can find plenty of icons online. I have a plan with icons8, find your icons there even if they are not free, send me the link and I will upload them on your page. All this is only if you like icons, I make this field optional.'}
              - { label: 'Text', name: 'content', widget: 'string', required: false, hint: 'This is the text that appears below the logo (or the Feature title if no logo). I made this field optional in case you are fine with having a title and or icon without text below.'}
          - label: 'Right-side features'
            name: 'right_side'
            widget: 'list'
            allow_add: false
            summary: '{{fields.title}} - {{fields.icon}} - {{field.content}}'
            fields:
              - { label: 'Feature Title', name: 'title', widget: 'string', hint: 'Name of this feature'}
              - { label: 'Icon', name: 'icon', widget: 'image', required: false, hint: 'Find an icon that comes with your feature. Icons are nice as they complement well the designs, and clients like visuals. You can find plenty of icons online. I have a plan with icons8, find your icons there even if they are not free, send me the link and I will upload them on your page. All this is only if you like icons, I make this field optional.'}
              - { label: 'Text', name: 'content', widget: 'string', required: false, hint: 'This is the text that appears below the logo (or the Feature title if no logo). I made this field optional in case you are fine with having a title and or icon without text below.'}

      - label: 'Promo Settings'
        name: 'promo'
        widget: 'object'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'select', options: ["true", "false"], hint: 'Select true to activate the section on the homepage. Select false to make the section disappear.' }
          - { label: 'Image', name: 'image', widget: 'image', hint: 'Chose an image to illustrate this section'}
          - { label: 'Headline', name: 'title', widget: 'string', required: false, hint: 'This is the main headline for this section of your homepage, appearing in bold. I made this field optional in case you are fine with having just text but no headline above.' }
          - { label: 'Content', name: 'content', widget: 'string', required: false, hint: 'This is the text that appears below your headline. I made this field optional in case you are fine with having a headline without text below.'}

      - label: 'Products Settings'
        name: 'products'
        widget: 'products'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'select', options: ["true", "false"], hint: 'Select true to activate the section on the homepage. Select false to make the section disappear.'}
          - { label: 'Headline', name: 'title', widget: 'string', hint: 'This is the main headline for this section of your homepage, appearing in bold.'}

      - label: 'Subscription Settings'
        name: 'subscription'
        widget: 'subscription'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'select', options: ["true", "false"], hint: 'Select true to activate the section on the homepage. Select false to make the section disappear.'}
          - { label: 'Image', name: 'image', widget: 'image', hint: 'Chose an image to illustrate this section'}
          - { label: 'Headline', name: 'title', widget: 'string', required: false, hint: 'This is the main headline for this section of your homepage, appearing in bold. I made this field optional in case you are fine with having just text but no headline above.'}
          - { label: 'Content', name: 'content', widget: 'string', required: false, hint: 'This is the text that appears below your headline. I made this field optional in case you are fine with having a headline without text below.'}
          - { label: "Text inside field", name: 'placeholder', widget: 'string', hint: 'Default to Your Email Address Here, but you can formulate it as you like.'}

      - label: 'Testimonial Settings'
        name: 'testimonial'
        widget: 'testimonial'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'select', options: ["true", "false"], hint: 'Select true to activate the section on the homepage. Select false to make the section disappear.' }
          - { label: 'Headline', name: 'title', widget: 'string', hint: 'This is the main headline for this section of your homepage, appearing in bold.'}
          - label: 'Testimonial list'
            name: 'testimonial_item'
            widget: 'list'
            allow_add: true
            summary: '{{fields.name}} - {{fields.designation}} - {{field.image}} - {{field.content}}'
            fields:
              - { label: 'Name of reviewer', name: 'name', widget: 'string', hint: 'Type the name of the client providing the testimony.'}
              - { label: 'Who is reviewer', name: 'designation', widget: 'string', required: false, hint: 'provide a few words presentation of this person if you want too. Leave it empty otherwise, this field is optional.'}
              - { label: 'Picture of reviewer', name: 'image', widget: 'image', required: false, hint: 'I made this field optional, but reviews online are much more powerful if there is a picture of the reviewer. Testimony can still be fake, but with a picture potential clients can relate better.'}

  - name: 'productssection'
    label: 'Products Main Page'
    description: 'You can edit here your Products Main page'
    folder: 'content/english/products'
    create: false
    editor:
      preview: true
    filter: {field: "mainsection", value: "true"}
    fields:
      - { label: 'Page Title and SEO Title', name: 'title', widget: 'string', hint: 'This is the Title that will apear on the related page, and also your SEO title that may appear in Google search results.' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'This is your SEO description, include keywords if possible, none of this will appear on your website but may appear in Google search results.' }
  - name: 'myproducts'
    label: 'My Products'
    description: 'You can edit here info regarding each of your products'
    folder: 'content/english/products'
    create: true
    editor:
      preview: true
    filter: {field: "mainsection", value: "false"}
    fields:
      - { label: 'Article Title and Article SEO Title', name: 'title', widget: 'string', hint: 'This is the Title that will apear on the related page, and also your SEO title that may appear in Google search results.' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'This is the description of your product, and also your SEO description + include keywords if possible, this may appear in Google search results.' }
      - { label: 'Product order', name: 'weight', widget: 'number', hint: 'This is where you reorganize the order in which your products appear on your page. 1 will apear 1st, 2 will be 2nd etc.'}
      - { label: 'Main picture', name: 'mainimage', widget: 'image', hint: 'This is the main picture of your product, the one clients can see from the Products Main Page' }
      - { label: 'Image loading speed', name: 'loading', widget: 'select', options: ["lazy", "eager"], hint: 'Choose "eager" for the 4 products placed on top of your page + choose "lazy" for all following products. That way images of products number 5 and beyond will load ONLY when client scrolls the page. This will help a lot with the Website Speed and SEO Performance.' }
      - { label: 'Other Pictures', name: 'images', widget: 'list', summary: '{{fields.image}}', field: {label: Image, name: image, widget: image}, hint: 'Add here the main picture again please, plus up to 3 more pictures of your product, so clients can see it from different angles' }
      - { label: 'Price', name: 'price', widget: 'number', hint: 'Price of your product' }
      - { label: 'Discount Price', name: 'discount_price', widget: 'number', required: false, hint: 'Discounted Price of your product if you want client to see the Price crosses and this discounted price appearing in red. Leave this field empty if you do not wish to use this feature.' }
      - { label: 'Colors', name: 'colors', widget: 'select', multiple: true, options: ["black", "white", "gray", "blue", "yellow", "red", "purple", "pink", "brown"], hint: 'Colors of your product' }
      - { label: 'Sizes', name: 'sizes', widget: 'select', multiple: true, options: ["small", "medium", "large"], hint: 'Sizes of your product' }
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Content for your product page + talk about your product + dont forget to insert a few keywords' }

  - name: 'sectionblog'
    label: 'Blog main page'
    description: 'You can edit here the main page of Blog, mainly its title and SEO description'
    folder: 'content/english/blog'
    create: false
    editor:
      preview: true
    filter: {field: "mainsection", value: "true"}
    fields:
      - { label: 'Page Title and SEO Title', name: 'title', widget: 'string', hint: 'This is the Title that will apear on the related page, and also your SEO title that may appear in Google search results.' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'This is your SEO description, include keywords if possible, none of this will appear on your website but may appear in Google search results.' }
  - name: 'myarticles'
    label: 'My Blog Articles'
    description: 'You can edit here each article of your blog'
    folder: 'content/english/blog'
    create: true
    editor:
      preview: true
    filter: {field: "mainsection", value: "false"}
    fields:
      - { label: 'Article Title and Article SEO Title', name: 'title', widget: 'string', hint: 'This is the Title that will apear on the related page, and also your SEO title that may appear in Google search results.' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'This is the description of your article, and also your SEO description + include keywords if possible, this may appear in Google search results.' }
      - { label: 'Article order', name: 'weight', widget: 'number', hint: 'This is where you reorganize the order in which your articles appear on your page. 1 will apear 1st, 2 will be 2nd etc.'}
      - { label: 'Illustration', name: 'image', widget: 'image', hint: 'Illustrate your article with a picture' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Page content + add a few pics if necessary + dont forget to insert a few keywords' }
      
  - name: 'sectioncontact'
    label: 'Contact Page'
    description: 'You can edit your contact page (except for the contact form, which is hard-coded).'
    folder: 'content/english/contact'
    create: false
    editor:
      preview: true
    fields:
      - { label: 'Contact page SEO Title', name: 'title', widget: 'string', hint: 'This is your SEO title that may appear in Google search results.' }
      - { label: 'SEO Description', name: 'description', widget: 'string', hint: 'This is your SEO description + include keywords if possible, this may appear in Google search results.' }
      - label: 'Office settings'
        name: 'office'
        description: 'Here is the section where you can mention your contact details.'
        widget: 'object'
        fields:
        - { label: 'Title', name: 'title', widget: 'string', hint: 'This is the Title that will appear on top of the Contact page'}
        - { label: 'Mobile', name: 'mobile', widget: 'string', required: false, hint: 'This is your mobile number, leave it empty and the field will disappear from the Contact page.'}
        - { label: 'email', name: 'email', widget: 'string', required: false, hint: 'This is your email address, leave it empty and the field will disappear from the Contact page.'}
        - { label: 'Location', name: 'location', widget: 'string', required: false, hint: 'This is your location, leave it empty and the field will disappear from the Contact page.'}
        - { label: 'Content', name: 'content', widget: 'string', hint: 'This is the content that will appear just below your contact details.'}
      - label: 'Opening Hours'
        name: 'opening_hour'
        description: 'This section is optional. If you leave it empty, nothing will appear on the website. Otherwise you can use it to mention Shipping, Support, Refund Policy etc..'
        widget: 'object'
        fields:
        - { label: 'Title', name: 'title', widget: 'string', required: false, hint: 'This is the Title that might appear on the right side of your Contact details. It was designed for Opening Hours but your can do whatever you want with it really (Shipping, Support hours..). If you leave these fields empty, nothing will appear on the right side of your contact details.'}
        - { label: 'Day and Time', name: 'day_time', widget: 'string', required: false, hint: 'This is where you can announce your Support Hours, shipping details or else. If you leave these fields empty, nothing will appear on the right side of your contact details.'}

  - name: 'sectionprivacypolicy'
    label: 'Privacy Policy page'
    description: 'You can edit your Privacy Policy page.'
    folder: 'content/english/privacy-policy'
    create: false
    editor:
      preview: true
    fields:
      - { label: 'Privacy Policy Title', name: 'title', widget: 'string', hint: 'This is the title of your page, most likely Privacy Policy (or anything else you like). This will appear on top of your page.' }
      - { label: 'SEO Description', name: 'description', widget: 'string', hint: 'This is your SEO description + this will not appear on your webpage, no need to insert keywords in Privacy Policy, we just make Google happy as it wants every webpage on the web to include a decription.' }
      - { label: 'Content', name: 'content', widget: 'string', hint: 'This is the content, details of your Privacy Policy.'}

  - name: 'sectiontermsandconditions'
    label: 'Terms and Conditions page'
    description: 'You can edit your Terms and Conditions page.'
    folder: 'content/english/terms-conditions'
    create: false
    editor:
      preview: true
    fields:
      - { label: 'Terms and Conditions Title', name: 'title', widget: 'string', hint: 'This is the title of your page, most likely Terms and Conditions (or anything else you like). This will appear on top of your page.' }
      - { label: 'SEO Description', name: 'description', widget: 'string', hint: 'This is your SEO description + this will not appear on your webpage, no need to insert keywords in Terms and Conditions, we just make Google happy as it wants every webpage on the web to include a decription.' }
      - { label: 'Content', name: 'content', widget: 'string', hint: 'This is the content, details of your Privacy Policy.'}